# .travis.yml file for an R project.  See:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh install_r rJava

script: 
  - R CMD INSTALL .
  - Rscript -e "require(rJava); require(testthat); require(SqlRender); test_package('SqlRender')"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change
    