language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - sudo R CMD javareconf
  - ./travis-tool.sh install_r_binary rJava
  - ./travis-tool.sh install_deps

script: 
  - ./travis-tool.sh run_tests
#  - R CMD INSTALL .
#  - Rscript -e "require(rJava); require(testthat); require(SqlRender); test_package('SqlRender')"

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change
    